isPublic: false
name: Posts
scope:
  - 'sites.58ccb571-6c72-449f-8e7b-6f43c5d416b3:read' # Starter Nuxt
  - 'sections.3e2a1a6f-88ea-477b-936d-39393f2d594f:read' # Posts
  - 'sections.3e2a1a6f-88ea-477b-936d-39393f2d594f:edit' # Posts
  - 'sections.3e2a1a6f-88ea-477b-936d-39393f2d594f:create' # Posts
  - 'sections.3e2a1a6f-88ea-477b-936d-39393f2d594f:save' # Posts
  - 'sections.3e2a1a6f-88ea-477b-936d-39393f2d594f:delete' # Posts
