baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Starter Nuxt'
primary: true
siteGroup: 6d0d3aa4-84be-441d-8fcc-2ab2d6db2503 # Starter starter
sortOrder: 1
