defaultPlacement: end
enableVersioning: true
entryTypes:
  - 697da4c2-e02f-4f49-9d76-e22609ceda25 # Page
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{{ alias(''@preview'') }}/{uri}'
propagationMethod: all
siteSettings:
  58ccb571-6c72-449f-8e7b-6f43c5d416b3: # Starter Nuxt
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: blog
type: single
