defaultPlacement: end
enableVersioning: true
entryTypes:
  - 697da4c2-e02f-4f49-9d76-e22609ceda25 # Page
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - Homepage
      -
        - urlFormat
        - '{uri}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  58ccb571-6c72-449f-8e7b-6f43c5d416b3: # Nuxt Starter
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
