defaultPlacement: end
enableVersioning: true
entryTypes:
  - 697da4c2-e02f-4f49-9d76-e22609ceda25 # Page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{uri}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  58ccb571-6c72-449f-8e7b-6f43c5d416b3: # Nuxt Starter
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{parent.uri ?? null}/{slug}'
structure:
  maxLevels: null
  uid: 97fc32ea-6e86-45dd-b3dd-97cdc4360518
type: structure
