columnSuffix: null
handle: navigation
instructions: null
name: Navigation
searchable: false
settings:
  createButtonLabel: 'New page'
  entryTypes:
    - b1b93579-e9e1-44de-9199-f7c9c50c51ef
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
